export * from './dashboard/dashboard.component'
export * from './header/header.component';
export * from './home/home.component';
export * from './login/login.component';
export * from './profile/profile.component';
export * from './register/register.component';
export * from './add-studyset/add-studyset.component';
export * from './studyset/studyset.component';
export * from './card/card.component';
export * from './flashcard/flashcard.component';
export * from './test/test.component';
